"""Lidya TTS - Made by SunWater_"""

# Imports
import dimits
from pydub import AudioSegment
from pydub.playback import play

# Main class
class TTS:
    """
    Main TTS Lib for Lidya."""

    def __init__(self, model):
        """
         Initialize the Dimits object. This is the constructor for the Vehicle class.
           You need to call this before you use the Vehicle class.
        """
        self.model = dimits.TextToSpeechModel(f'./models/{model}/{model}.onnx')

    def generate_audio(self, text, location):
        """
         Generate and save audio file. This method is used to generate a sound file
         from text. The file is saved to location
        """
        generated_bytes = self.model.synthesize(text)
        with open(location, 'ab') as f:
            f.write(generated_bytes)

        return location

    def play_generate_audio(self, text):
        """
         Play a generated audio. This is a convenience method for use in tests that want to
         play audio from a text that has been generated by the user
        """

        self.generate_audio(text, './cache/tts_output.wav')
        song = AudioSegment.from_file("./cache/tts_output.wav", format="wav")
        play(song)
