"""Lidya TTS - Made by SunWater_"""

# Imports
from dimits import Dimits

# Main class


class TTS:
    """
    Main TTS Lib for Lidya."""

    def __init__(self, lang, voice):
        """
         Initialize the Dimits object. This is the constructor for the Vehicle class.
           You need to call this before you use the Vehicle class.
         
         @param lang - language of the voice e. g. " de "
         @param voice - voice of the voice e. g. " mus
        """
        self.lang = lang
        self.voice = voice
        self.model = lang + "-" + voice

        self.dt = Dimits(self.model)

    def generate_audio(self, text, location):
        """
         Generate and save audio file. This method is used to generate a sound file 
         from text. The file is saved to location
         
         @param text - text to be played in sound file
         @param location - location where to save sound file. It will be saved to 
         this location
         
         @return location where audio file was saved to. It will be saved to this
         location after completion of the program
        """
        self.dt.text_2_audio_file(
            text, location.split("/")[-1], "/".join(location.split("/")[0:-1])
        )
        return location

    def play_generate_audio(self, text):
        """
         Play a generated audio. This is a convenience method for use in tests that want to 
         play audio from a text that has been generated by the user
         
         @param text - The text that should be
        """
        self.dt.text_2_speech(text)


# Tests
if __name__ == "__main__":
    tts = TTS("fr_FR", "siwis-medium")
    tts.generate_audio("salut les amis", "./test.wav")
    tts.play_generate_audio("Salut les amis")
